---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubelock
  namespace: kubelock
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "create", "update"]