---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubelock
subjects:
- kind: ServiceAccount
  name: kubelock